version: "3"

services:
  phoenix:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nfl_rushing_dev
